org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.145.1+26.1

mod_version=1.7
maven_group=thunder.hack
archives_base_name=thunderhack

orbit_version=0.2.3
netty_version=4.1.90.Final
baritone_version=1.21.1-SNAPSHOT
